RootWidget:

<RootWidget>:
    screen_manager: screen_manager
    ScreenManager:
        id: screen_manager
        current: 'main_menu'
        pos: root.pos
        size: root.size
        MainMenu:
            screen_manager: root
            size: root.size
            pos: root.pos
        OtherMenu:
            screen_manager: root
            size: root.size
            pos: root.pos
    
<MainMenu>:
    screen_manager: self.screen_manager
    TextInput:
        text: 'WELCOME TO CODERUNNER!  CHOOSE YOUR LEVEL'
        pos_hint: {'x': .25}
    Image:
        source: 'logo.png'
        keep_ratio: False
        allow_stretch: True
        opacity: 0.8
        size_hint: 0.3, 0.4
        pos_hint: {'x': 0.35, 'y': 0.5}
    FloatLayout:
        Button:
            text: 'Easy'
            size_hint: (.3, .2)
            pos_hint: {'x': .35, 'y': .4}
            on_press: root.screen_manager.set_state(root.name)
        Button:
            text: 'Medium'
            size_hint: (.3, .2)
            pos_hint: {'x': .35, 'y': .2}
            on_press: root.screen_manager.set_state(root.name)
        Button:
            text: 'Hard'
            size_hint: (.3, .2)
            pos_hint: {'x': .35, 'y': .0}
            on_press: root.screen_manager.set_state(root.name)
        

<OtherMenu>:
    screen_manager: self.screen_manager
    FloatLayout:
        Button:
            text: 'Other'
            size_hint: (.4, .2)
            pos_hint: {'x': .3, 'y': .4}
            on_press: root.screen_manager.set_state(root.name)
